services: 

  authelia: 
    image: authelia/authelia
    container_name: "authelia-acme"
    volumes: 
      - ./authelia/config:/config
    networks: 
      - net
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.acme.se`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=myresolver"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=http://authelia.acme.se"
      - "traefik.http.middlewares.authelia.forwardauth.trustforwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email"
    expose: 
      - 9091
    restart: unless-stopped
    environment: 
      - TZ=Europe/Stockholm
  
  traefik: 
    image: "traefik:latest"
    container_name: "traefik-acme"
    command: 
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=psopena@kth.se"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.acme.se`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$14C1oB3W$1BfKVrmaMtmGp3u62v2yR/"
    networks:
      - net

  whoami_unsecure: 
    image: traefik/whoami
    container_name: whoami_unsecure
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.whoami_unsecure.rule=Host(`unsecure.whoami.acme.se`)"
      - "traefik.http.routers.whoami_unsecure.entrypoints=websecure"
      - "traefik.http.routers.whoami_unsecure.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami_unsecure.tls=true"
      - "traefik.http.routers.whoami_unsecure.middlewares=authelia@docker"
  
  whoami_secure:
    image: traefik/whoami
    container_name: whoami_secure
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.whoami_secure.rule=Host(`secure.whoami.acme.se`)"
      - "traefik.http.routers.whoami_secure.entrypoints=websecure"
      - "traefik.http.routers.whoami_secure.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami_secure.tls=true"
      - "traefik.http.routers.whoami_secure.middlewares=authelia@docker"
    
  webserver: 
    build:
        context: './webserver'
        dockerfile: 'Dockerfile'
    container_name: 'webserver-acme'
    networks: 
      - net
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`webserver.acme.se`)"
      - "traefik.http.routers.webserver.entrypoints=websecure"
      - "traefik.http.routers.webserver.tls.certresolver=myresolver"
      - "traefik.http.routers.webserver.tls=true"
      - "traefik.http.routers.webserver.middlewares=authelia@docker"


networks: 
  net: 
    driver: bridge
      
    