server.port: 9091
log.level: debug
jwt_secret: insecure_secret

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldaps://ipasrv.acme.se
    start_tls: false
    tls:
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: dc=acme,dc=se
    username_attribute: uid
    additional_users_dn: cn=users,cn=accounts
    users_filter: "(&({username_attribute}={input})(|(objectClass=person)(objectClass=posixAccount)))"
    additional_groups_dn: cn=groups,cn=accounts
    groups_filter: "(&(member=uid={input},cn=users,cn=accounts,dc=acme,dc=se)(objectClass=groupOfNames))"
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: givenName
    user: uid=admin,cn=users,cn=accounts,dc=acme,dc=se
    password: NilsSmokesCoke2025!
    
totp:
  disable: true
  
session:
  name: authelia_session
  domain: acme.se
  same_site: lax
  secret: unsecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration:  1M

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: one_factor
  rules:
    - domain: unsecure.whoami.acme.se
      policy: bypass
    - domain: webserver.acme.se
      policy: one_factor
    - domain: secure.whoami.acme.se
      policy: one_factor

notifier:
  filesystem:
    filename: /config/notification.txt