jwt_secret: insecure_secret
default_redirection_url: https://authelia.acme.se

log:
  level: debug

totp: 
  disable: true

authentication_backend:
  file: 
    path: /config/users_database.yml

access_control: 
  default_policy: deny
  rules: 
    - domain: unsecure.whoami.acme.se
      policy: bypass
    - domain: secure.whoami.acme.se
      policy: one_factor

session: 
  name: authelia_session
  domain: acme.se
  secret: unsecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration:  1M

regulation: 
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

identity_validation:
  reset_password: {}
    
notifier:
  filesystem:
    filename: /config/notification.txt

