server.port: 9091
log.level: debug
jwt_secret: insecure_secret

authentication_backend:
  file:
    path: /config/users_database.yml
    
totp:
  disable: true
  
session:
  name: authelia_session
  domain: acme.se
  same_site: lax
  secret: unsecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration:  1M

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: one_factor
  rules:
    - domain: unsecure.whoami.acme.se
      policy: bypass
    - domain: webserver.acme.se
      policy: one_factor
    - domain: secure.whoami.acme.se
      policy: one_factor

notifier:
  filesystem:
    filename: /config/notification.txt