---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  geek:
    displayname: "<DISPLAYNAME>"
    password: "$argon2id$v=19$m=65536,t=1,p=8$TktzbWhSZTRtMHozdGRIVQ$2e44kGoDwWVCxeoovyEor1GJ05lCBNmMYxL3UbqLb64"
    email: geek@example.com
    groups:
      - admins
      - dev
  admin:
      displayname: "Administrator"
      password: "$argon2id$v=19$m=65536,t=3,p=4$uweMSVDj6uc8gL7EVVNFoQ$cUYaC0XEHSoyOJvrWLC1ETsOUtim+32iXfSVsj983Cw" ## Password: admin
      email: paulasopenacoello@gmail.com
      groups:
        - admins
        - dev
...
